DATA:
  NUM_FRAMES: 8
UNIFORMERV2:
  BACKBONE: 'uniformerv2_b16'
  N_LAYERS: 4
  N_DIM: 768
  N_HEAD: 12
  MLP_FACTOR: 4.0
  BACKBONE_DROP_PATH_RATE: 0.
  DROP_PATH_RATE: 0.
  MLP_DROPOUT: [0.5, 0.5, 0.5, 0.5]
  CLS_DROPOUT: 0.5
  RETURN_LIST: [8, 9, 10, 11]
  NO_LMHRA: True
  TEMPORAL_DOWNSAMPLE: False
  PRETRAIN: './pretrain_models/k600_k710_uniformerv2_b16_8x224.pyth'
  DW_REDUCTION: 1.5
  DOUBLE_LMHRA: True
  FROZEN: True
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
MODEL:
  NUM_CLASSES: 600
  ARCH: uniformerv2
  MODEL_NAME: Uniformerv2
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  USE_CHECKPOINT: False
  CHECKPOINT_NUM: [0]